In [7]:
import numpy as np

# Item - Item based filtering - imp features are skills, job description

# cosine similarity approach between job decs and students experience

In [40]:
des1=["I required java developer, Android and web dev for my project java"]
des2=["i like java,web and Android "]
des3=des1+(des2)
des3

['I required java developer, Android and web dev for my project java',
 'i like java,web and Android ']

#  function to convert text to vectors (BOW)

In [46]:
vocab = {}
i = 1


x = des1[0].split(" ")

for word in x:
    if word in vocab:
        continue
    else:
        vocab[word]=i
        i+=1

print(vocab)

{'I': 1, 'required': 2, 'java': 3, 'developer,': 4, 'Android': 5, 'and': 6, 'web': 7, 'dev': 8, 'for': 9, 'my': 10, 'project': 11}


In [47]:
x=des2[0].split(" ")

for word in x:
    if word in vocab:
        continue
    else:
        vocab[word]=i
        i+=1

In [48]:
print(vocab)

{'I': 1, 'required': 2, 'java': 3, 'developer,': 4, 'Android': 5, 'and': 6, 'web': 7, 'dev': 8, 'for': 9, 'my': 10, 'project': 11, 'i': 12, 'like': 13, 'java,web': 14, '': 15}


In [49]:
one = ['1.txt']+[0]*len(vocab)
one

['1.txt', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

In [53]:

x =des1[0].split(" ")
    
for word in x:
    one[vocab[word]]+=1
    
one

['1.txt', 1, 3, 4, 3, 1, 1, 1, 1, 1, 1, 1, 2, 0, 0, 0]

In [54]:
two = ['2.txt']+[0]*len(vocab)


x = des2[0].split()
    
for word in x:
    two[vocab[word]]+=1

In [55]:
two

['2.txt', 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0]

# des1=job desc  and des2=student experience

# using sklearn inbuilt function

In [59]:
des1="I required java developer, Android and web dev for my project java"
des2="I like java,web and Android "

docs=[des1,des2]

# countvectorizer( BOW)

In [71]:

from sklearn.feature_extraction.text import CountVectorizer
Vectorizer = CountVectorizer()
Vectorizer.fit_transform(docs)

<2x11 sparse matrix of type '<class 'numpy.int64'>'
	with 15 stored elements in Compressed Sparse Row format>

In [72]:
print(Vectorizer.vocabulary_)

{'required': 9, 'java': 5, 'developer': 3, 'android': 1, 'and': 0, 'web': 10, 'dev': 2, 'for': 4, 'my': 7, 'project': 8, 'like': 6}


# for making tfidf matrix 1.find countvectorizer -->  tfidf transformer
#                                         2. use tfidf vectorizer

In [73]:
tf_matrix = Vectorizer.transform(docs).toarray()
print(tf_matrix)

[[1 1 1 1 1 2 0 1 1 1 1]
 [1 1 0 0 0 1 1 0 0 0 1]]


In [68]:
 from sklearn.feature_extraction.text import TfidfTransformer
 tfidfTran = TfidfTransformer(norm="l2")
 tfidfTran.fit(tf_matrix)
 print(tfidfTran.idf_)

[1.         1.         1.40546511 1.40546511 1.40546511 1.
 1.40546511 1.40546511 1.40546511 1.40546511 1.        ]


In [75]:
tfidf_matrix = tfidfTran.transform(tf_matrix)
print(tfidf_matrix.toarray())

[[0.23031454 0.23031454 0.32369906 0.32369906 0.32369906 0.46062909
  0.         0.32369906 0.32369906 0.32369906 0.23031454]
 [0.4090901  0.4090901  0.         0.         0.         0.4090901
  0.57496187 0.         0.         0.         0.4090901 ]]


In [76]:
from sklearn.feature_extraction.text import TfidfVectorizer
TfidfVec = TfidfVectorizer()
def cos_similarity(textlist):
    tfidf = TfidfVec.fit_transform(textlist)
    return (tfidf * tfidf.T).toarray()
cos_similarity(docs)

array([[1.      , 0.471097],
       [0.471097, 1.      ]])

# cosine similarity

In [77]:
sim=cos_similarity(docs)

In [78]:
sim[0][1]

0.4710970045156096

# Jacard similarity

In [85]:
def get_jacard(s1,s2):
    a=set(s1.split())
    b=set(s2.split())
    c=a.intersection(b)
    return float(len(c))/(len(a)+len(b)-len(c))

des1=" java python php ml"              #skills required in job
des2="java php"                         # student's skills

p=get_jacard(des1,des2)

In [86]:
p

0.5

# distance=1-similarity


In [90]:
# for description matching  cosine similarity
#for skills matchin jacard similarity

desc_dis=1-sim[0][1]            
skills_dis=1-p

In [91]:
desc_dis

0.5289029954843905

In [92]:
skills_dis

0.5